### ISSUE TITLE
Cannot install with the given command

### ISSUE THREAD

**Issue by bozbalci** [rr-/drill#1]
This is the output of `pip install drillsrs`:

Collecting drillsrs
  Could not find a version that satisfies the requirement drillsrs (from versions: )
No matching distribution found for drillsrs

**Comment by rr-** [comment]
Just published 0.2 with recent improvements: https://pypi.python.org/pypi/drillsrs/0.2

Hopefully, it should appear soon in PIP. Meanwhile I've added instruction in the README how to install it by hand.
