### ISSUE TITLE
algrithm

### ISSUE THREAD

**Issue by runlow** [rr-/drill#14]
@rr- although you explain how the program works you don't explain the rationale behind how it works

I think it took Wozniak many years to come up with [SM2](https://www.supermemo.com/en/archives1990-2015/english/ol/sm2)

Are you sure that the algorithm you implemented is the most optimal one? SM2 relies on multiple scores in a row.

For example with SM2 if you rank very high a card you ranked low before - it won't delay the next rep right off the bat.

**Comment by runlow** [comment]
Yours seems simpler but maybe it's better, no idea. Do you find that it's working well?

**Comment by rr-** [comment]
Simplicity :) It was working while I was still using it.

**Comment by runlow** [comment]
If you don't use it any more then how would you know if it works out well long-term?

**Comment by rr-** [comment]
Because I used it for ~2 years
