### ISSUE TITLE
"db.py:114: SAWarning: implicitly coercing SELECT"

### ISSUE THREAD

**Issue by electronoob** [rr-/drill#16]
e@e:~/Downloads$ /home/e/.local/bin/drill-srs 
/home/e/.local/lib/python3.8/site-packages/drillsrs/db.py:95: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.

there's a lot of these warnings.

**Comment by samgriesemer** [comment]
Completely informal response (i.e. haven't wrapped this in a PR), but you can follow the warnings and add a `.scalar_subquery()` call at the end of each of the `SELECT` queries. Seems like it's just a clashing change in a newer version of `sqlalchemy`. For me, replacing lines 116-140 of the `db.py` file with

```python
first_answer_date = sa.orm.column_property(
    sa.sql.expression.select([sa.sql.expression.func.min(UserAnswer.date)])
    .where(UserAnswer.card_id == id)
    .correlate_except(UserAnswer)
    .scalar_subquery()
)

total_answer_count = sa.orm.column_property(
    sa.sql.expression.select([sa.sql.expression.func.count(UserAnswer.id)])
    .where(UserAnswer.card_id == id)
    .correlate_except(UserAnswer)
    .scalar_subquery()
)

correct_answer_count = sa.orm.column_property(
    sa.sql.expression.select([sa.sql.expression.func.count(UserAnswer.id)])
    .where(UserAnswer.card_id == id)
    .where(UserAnswer.is_correct == 1)
    .correlate_except(UserAnswer)
    .scalar_subquery()
)

incorrect_answer_count = sa.orm.column_property(
    sa.sql.expression.select([sa.sql.expression.func.count(UserAnswer.id)])
    .where(UserAnswer.card_id == id)
    .where(UserAnswer.is_correct == 0)
    .correlate_except(UserAnswer)
    .scalar_subquery()
)
```
fixed the warnings (although those might not be the same lines for your version).

**Comment by rr-** [comment]
Thanks @samgriesemer

**Comment by electronoob** [comment]
thanks a lot, i appreciate the super fast response, sorry for my slowness but updated to latest version now. thank you!
