### ISSUE TITLE
What's the decks format?

### ISSUE THREAD

**Issue by seniorivn** [rr-/drill#3]
I was going to write something like your drill by myself, but you already did it, thank you.

what is the best way to generate decks automatically? is it anki compatible?(i don't care, i just need the format)

**Comment by rr-** [comment]
The deck format is a simple SQLite database, schema of which can be inspected with any graphical browser / editor. It's left deliberately undocumented, but the column and table names are pretty intuitive.

There's no anki integration since I didn't need it yet.
